#: include screens/login/login.kv
#: include screens/login/reset.kv
#: include screens/dashboard/dashboard.kv
#: include screens/dashboard/screens/inventory.kv
#: include screens/dashboard/screens/financial.kv
#: include screens/dashboard/screens/sales.kv
#: include screens/dashboard/screens/assets.kv
#: include screens/dashboard/screens/analytics.kv


ScreenManager:
    LoginScreen:
        name: 'login'

    ResetScreen:
        name: 'reset'

    DashboardScreen:
        name: 'dashboard'
